
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed May 31 23:57:50 CST 2023
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IdentClasePaquete = 66;
  public static final int Op_relacional = 47;
  public static final int Op = 20;
  public static final int S_linea = 67;
  public static final int Coma = 58;
  public static final int Ars = 37;
  public static final int Llave_c = 54;
  public static final int Op_booleano = 50;
  public static final int Llave_a = 53;
  public static final int Lista = 25;
  public static final int Plub = 6;
  public static final int T_dato = 10;
  public static final int Prit = 7;
  public static final int Ejt = 16;
  public static final int Detn = 21;
  public static final int Corchete_c = 56;
  public static final int Ctg = 9;
  public static final int Corchete_a = 55;
  public static final int Tx = 11;
  public static final int Strg = 36;
  public static final int Punto = 59;
  public static final int Pckg = 3;
  public static final int Imprt = 4;
  public static final int Sysm = 38;
  public static final int Hrd = 29;
  public static final int Condcc = 15;
  public static final int Division = 45;
  public static final int Cjt = 26;
  public static final int Jtcs = 5;
  public static final int Fcn = 33;
  public static final int Numero_negativo = 64;
  public static final int Cero = 24;
  public static final int Cadena = 65;
  public static final int Parentesis_c = 52;
  public static final int Rtr = 34;
  public static final int Falso = 61;
  public static final int Parentesis_a = 51;
  public static final int P_coma = 57;
  public static final int EOF = 0;
  public static final int Rtn = 32;
  public static final int Stc = 12;
  public static final int Itp = 19;
  public static final int error = 1;
  public static final int Itn = 22;
  public static final int Impr = 40;
  public static final int Op_atribucion = 48;
  public static final int Numero_positivo = 63;
  public static final int ERROR = 68;
  public static final int Rptr = 18;
  public static final int Min = 35;
  public static final int Gen = 28;
  public static final int Op_logico = 46;
  public static final int Cond = 14;
  public static final int Fnz = 31;
  public static final int Vid = 13;
  public static final int Mtrt = 17;
  public static final int Reserv = 27;
  public static final int Identificador = 62;
  public static final int Ptg = 8;
  public static final int Exc = 30;
  public static final int Resta = 43;
  public static final int Verdadero = 60;
  public static final int Multiplicacion = 44;
  public static final int Trp = 23;
  public static final int Op_incremento = 49;
  public static final int Suma = 42;
  public static final int Igual = 41;
  public static final int Ot = 39;
  public static final int Comillas = 2;
}

